### ISSUE TITLE
Reporte de practica individual

### ISSUE THREAD

**Issue by MariaC232** [SistemasTecTlaxiaco/practica-de-visual-studio-MariaC232#3]
[Practicaindividual.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visual-studio-MariaC232/files/6191301/Practicaindividual.pdf)

**Comment by Ferch0419** [comment]
Revisado por Fernando Miguel López.
Calificación: 20/20.

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
